---
# Loading vars
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

# Install Shorewall server
- name: Install the required  packages in Redhat derivatives
  yum: name={{ shorewall_package }} state=present
  when: ansible_os_family == 'RedHat'

- name: Install the required packages in Debian derivatives
  apt: name={{ shorewall_package }} state=present update_cache=yes
  when: ansible_os_family == 'Debian'

# Generate configuration
- name: Generate zones
  template: src=zones.j2 dest={{ shorewall_zones_file }}
  register: shorewall_zone

- name: Generate interfaces
  template: src=interfaces.j2 dest={{ shorewall_interfaces_file }}
  register: shorewall_interface

- name: Generate policy
  template: src=policy.j2 dest={{ shorewall_policy_file }}
  register: shorewall_policy

- name: Generate rules
  template: src=rules.j2 dest={{ shorewall_rules_file }}
  register: shorewall_rules_conf

- name: Generate masq
  template: src=masq.j2 dest={{ shorewall_masq_file }}
  register: shorewall_masq

- name: Generate shorewall.conf 
  template: src=shorewall.conf.j2 dest={{ shorewall_config_file }}
  register: shorewall_conf

# Generate service configuration
- name: Generate Shorewall service conf
  template: src=shorewall.j2 dest={{ shorewall_service_config }} owner=root group=root
  register: shorewall_service_conf

# Reload service
- name: Restart Shorewall service
  service: name={{ shorewall_service }} state=restarted
  when: shorewall_zone.changed or shorewall_interface.changed or shorewall_policy.changed or shorewall_rules_conf.changed or shorewall_masq.changed or shorewall_conf.changed or shorewall_service_conf.changed

# Enable Shorewall server
- name: Start the  Shorewall service
  service: name={{ shorewall_service }} state=started enabled=yes
